name: Bug提交
description: 如果您认为这是Bug，请填写该表单
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ZianTT
body:
  - type: markdown
    attributes:
      value: |
        感谢您提交Bug，请花两分钟时间填写下列表单便于我更快处理
  - type: input
    id: desc
    attributes:
      label: 描述这个Bug
      description: 清晰而简洁的描述这个Bug。
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 预期操作
      description: 清晰而简洁地描述你期望发生的事情。
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: 如果可以的话，尽可能添加屏幕截图来帮助解释你的问题。
  - type: dropdown
    id: version
    attributes:
      label: 问题版本
      description: 你是用的是哪个分支的版本？
      options:
        - main分支-Release
        - dev分支
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: 请输入程序输出的内容
      render: shell
  - type: checkboxes
    id: newest
    attributes:
      label: 我是最新版本
      description: 提交Issue前，请确认以下内容
      options:
        - label: 我确认这是该分支的最新版本且这是第一个针对该问题的Issue
          required: true
