name: CI

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: [codecov]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-latest]
        debug: [debug, distribution]
        include:
          - os: windows-latest
            build: SFES-Windows.exe
          - os: ubuntu-latest
            build: SFES-Linux
          - os: macos-13
            build: SFES-macOS-Intel
          - os: macos-latest
            build: SFES-macOS-Apple_Silicon
    runs-on: ${{ matrix.os }}
    env:
      debug: ${{ matrix.debug }}
      version: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Cython
        if: matrix.debug == 'distribution'
        run: pip install Cython

      - name: Run Cython
        if: matrix.debug == 'distribution'
        run: python setup_cython.py build_ext --inplace

      - name: Build Binary
        run: pyinstaller main.spec

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: dist/${{ matrix.debug }}-${{ github.ref_name }}-${{ matrix.build }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/${{ matrix.debug }}-${{ github.ref_name }}-${{ matrix.build }}
